# Generated by Django 5.1 on 2024-08-31 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='name',
            new_name='title',
        ),
    ]
