# Generated by Django 5.1 on 2024-08-31 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_name_game_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='genre',
            new_name='genres',
        ),
    ]
